from argparse import ArgumentParser, _SubParsersAction
from shade import OpenStackCloud

class CloudCleanerConfig(object):
    def __init__(self,
                 parser: ArgumentParser = None,
                 args: list = None): ...

    def add_subparser(self, name: str) -> _SubParsersAction: ...

    def set_args(self, args: list): ...

    def parse_args(self) -> ArgumentParser: ...

    def get_arg(self, name: str) -> any: ...

    def get_resource(self) -> str: ...

    def get_cloud(self): ...

    def get_shade(self) -> OpenStackCloud: ...

    def info(self, msg, *args): ...

    def debug(self, msg, *args): ...

    def warning(self, msg, *args): ...