class Fip(Resource):
    def __init__(self): ...

    def register(self, config: CloudCleanerConfig): ...

    def process(self, deletion: bool): ...

    def clean(self): ...

    def __filter_attached(self): ...

    def __filter_by_address(self): ...

    @classmethod
    def __filter_factory(cls, field: str, network: str): ...
