from datetime import timedelta


class Resource(object):
    def __init__(self, **kwargs): ...

    def register(self, config: CloudCleanerConfig): ...

    def process(self): ...

    def clean(self): ...

    def parse_interval(self, interval: str) -> timedelta: ...

    @classmethod
    def __parse_interval(cls, regex: str, interval: str): ...

    def _get_conn(self): ...

    def send_emails(self): ...

    def prep_deletion(self): ...


class UnimplementedError(Exception):
    ...
