name: Test code

"on":
  push: {}

jobs:
  collect:
    runs-on: ubuntu-latest
    outputs:
      envs: ${{ steps.envs.outputs.tox-envs }}
    steps:
      - uses: actions/checkout@v2
      - id: envs
        uses: greg-hellings/tox-list@v1

  test:
    needs:
      - collect
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: ${{ fromJson(needs.collect.outputs.envs) }}
    steps:
      - uses: actions/checkout@v2
      - uses: greg-hellings/tox-run@master
        with:
          tox-env: ${{ matrix.environment }}
